{% set name = "datamapplot" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datamapplot-{{ version }}.tar.gz
  sha256: 1a9082c30f77dbda5079973050bbe672d93ac10b11ec36c6750b9fff2194df3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy >=1.21
    - matplotlib-base >=3.8
    - scikit-learn >=1.1
    - pandas >=1.0
    - datashader >=0.16
    - colorspacious >=1.1
    - scikit-image >=0.22
    - numba >=0.56
    - pylabeladjust
    - requests
    - jinja2
    - rcssmin >=1.1.2
    - rjsmin >=1.2.2

test:
  imports:
    - datamapplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/TutteInstitute/datamapplot
  summary: Presentation and publication ready plots of data maps
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lmcinnes
