{% set name = "datamapplot" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datamapplot-{{ version }}.tar.gz
  sha256: fdceae6085a4aabdc7cd15ce81c34ff54cb77107f78afcaae7989462d7a62ac1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy >=1.21
    - matplotlib-base >=3.8
    - scikit-learn >=1.1
    - pandas >=1.0
    - datashader >=0.16
    - colorspacious >=1.1
    - scikit-image >=0.22
    - numba >=0.56
    - pylabeladjust
    - requests
    - jinja2

test:
  imports:
    - datamapplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/TutteInstitute/datamapplot
  summary: Presentation and publication ready plots of data maps
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lmcinnes
